-- Generated by `pnpm run db:verify` from the applied migrations.
-- Do not edit by hand. Migrations remain the executable source of truth.
-- Structure and privileges only; it never contains RSVP data.

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: default_rsvp_deadline(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.default_rsvp_deadline() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
BEGIN
    IF NEW.rsvp_deadline_utc IS NULL THEN
        NEW.rsvp_deadline_utc := NEW.event_date_utc - INTERVAL '14 days';
    END IF;
    RETURN NEW;
END;
$$;


--
-- Name: get_pending_purge_warnings(integer); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.get_pending_purge_warnings(p_days_before integer) RETURNS TABLE(wedding_slug text, admin_email text, purge_date timestamp with time zone)
    LANGUAGE sql SECURITY DEFINER
    SET search_path TO 'public', 'auth'
    AS $$
    SELECT i.wedding_slug, u.email, i.event_date_utc + INTERVAL '7 days'
    FROM public.invitations AS i
    JOIN public.invitation_admins AS ia ON ia.invitation_id = i.wedding_slug
    JOIN auth.users AS u ON u.id = ia.user_id
    WHERE i.purge_warning_sent_at IS NULL
      AND i.event_date_utc + INTERVAL '7 days' - (p_days_before || ' days')::interval <= now()
      AND i.event_date_utc + INTERVAL '7 days' > now();
$$;


--
-- Name: get_rsvp_status(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.get_rsvp_status(p_wedding_slug text) RETURNS TABLE(is_open boolean, deadline_utc timestamp with time zone, override text)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
    SELECT public.is_rsvp_open(inv.wedding_slug), inv.rsvp_deadline_utc, inv.rsvp_override
    FROM public.invitations AS inv
    WHERE inv.wedding_slug = p_wedding_slug;
$$;


--
-- Name: is_rsvp_open(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.is_rsvp_open(p_wedding_slug text) RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
    SELECT CASE inv.rsvp_override
        WHEN 'open' THEN true
        WHEN 'closed' THEN false
        ELSE now() < inv.rsvp_deadline_utc
    END
    FROM public.invitations AS inv
    WHERE inv.wedding_slug = p_wedding_slug;
$$;


--
-- Name: purge_all_expired_rsvp(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.purge_all_expired_rsvp() RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
    DELETE FROM public.rsvp_responses
    WHERE wedding_slug IN (
        SELECT wedding_slug FROM public.invitations
        WHERE event_date_utc + INTERVAL '7 days' < now()
    );
END;
$$;


--
-- Name: record_invitation_schedule_audit(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.record_invitation_schedule_audit() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
BEGIN
    IF NEW.rsvp_deadline_utc IS DISTINCT FROM OLD.rsvp_deadline_utc
        OR NEW.rsvp_override IS DISTINCT FROM OLD.rsvp_override THEN
        INSERT INTO public.admin_audit (entity, wedding_slug, action, actor_id)
        VALUES ('invitation', NEW.wedding_slug, 'schedule_changed', auth.uid());
    END IF;

    RETURN NEW;
END;
$$;


--
-- Name: record_rsvp_response_audit(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.record_rsvp_response_audit() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
    actor     UUID := auth.uid();
    performed TEXT;
BEGIN
    performed := CASE
        WHEN OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL THEN 'deleted'
        WHEN OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN 'restored'
        WHEN COALESCE(current_setting('app.rsvp_guest_correction', true), 'off') = 'on'
            THEN 'corrected'
        ELSE 'updated'
    END;

    INSERT INTO public.admin_audit (response_id, entity, wedding_slug, action, actor_id)
    VALUES (NEW.id, 'rsvp_response', NEW.wedding_slug, performed, actor);

    RETURN NEW;
END;
$$;


--
-- Name: require_rsvp_open(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.require_rsvp_open() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
    open_state BOOLEAN;
    found      BOOLEAN;
BEGIN
    IF current_user NOT IN ('anon', 'authenticated') THEN
        RETURN NEW;
    END IF;

    SELECT state.registered, state.is_open
    INTO found, open_state
    FROM public.rsvp_invitation_state(NEW.wedding_slug) AS state;

    IF NOT COALESCE(found, false) THEN
        RAISE EXCEPTION 'No invitation is registered for wedding_slug %', NEW.wedding_slug
            USING ERRCODE = 'RSVPU',
                  HINT = 'Run scripts/sync-invitation.ts against this project.';
    END IF;

    -- NULL cannot happen once the row is known to exist -- `is_rsvp_open` is total over an
    -- existing row -- but treating it as closed keeps the fail-closed default if that changes.
    IF NOT COALESCE(open_state, false) THEN
        RAISE EXCEPTION 'The RSVP for % is closed', NEW.wedding_slug
            USING ERRCODE = 'RSVPC';
    END IF;

    RETURN NEW;
END;
$$;


--
-- Name: resolve_rsvp_identity(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.resolve_rsvp_identity() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    intent      TEXT;
    base_key    TEXT;
    existing_id BIGINT;
    holders     INTEGER;
    next_mark   SMALLINT;
BEGIN
    intent := lower(btrim(COALESCE(NEW.submission_intent, '')));
    base_key := lower(btrim(NEW.full_name));

    -- Both are the trigger's to decide, never the caller's.
    NEW.submission_intent := NULL;
    NEW.identity_discriminator := NULL;

    SELECT count(*), min(id)
    INTO holders, existing_id
    FROM public.rsvp_responses
    WHERE wedding_slug = NEW.wedding_slug
      AND lower(btrim(full_name)) = base_key
      AND deleted_at IS NULL;

    IF holders = 0 THEN
        -- Nobody answered under this name. A 'namesake' claim with no original is simply a first
        -- answer, and saying so would only puzzle a guest who mistyped their own name once.
        RETURN NEW;
    END IF;

    IF intent = 'correction' THEN
        IF holders > 1 THEN
            RAISE EXCEPTION 'Several responses share the name % for %', NEW.full_name, NEW.wedding_slug
                USING ERRCODE = 'RSVPM',
                      HINT = 'Ask the couple to correct it: the row cannot be identified by name.';
        END IF;

        PERFORM set_config('app.rsvp_guest_correction', 'on', true);

        UPDATE public.rsvp_responses
        SET answers      = NEW.answers,
            form_id      = NEW.form_id,
            form_version = NEW.form_version,
            locale       = NEW.locale
        WHERE id = existing_id;

        PERFORM set_config('app.rsvp_guest_correction', 'off', true);

        RETURN NULL;
    END IF;

    IF intent = 'namesake' THEN
        SELECT COALESCE(max(identity_discriminator), 1) + 1
        INTO next_mark
        FROM public.rsvp_responses
        WHERE wedding_slug = NEW.wedding_slug
          AND lower(btrim(full_name)) = base_key
          AND deleted_at IS NULL;

        NEW.identity_discriminator := next_mark;
        RETURN NEW;
    END IF;

    RAISE EXCEPTION 'A response already exists under the name % for %', NEW.full_name, NEW.wedding_slug
        USING ERRCODE = 'RSVPD',
              HINT = 'Resubmit with submission_intent set to correction or namesake.';
END;
$$;


--
-- Name: rsvp_invitation_state(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.rsvp_invitation_state(p_wedding_slug text) RETURNS TABLE(registered boolean, is_open boolean)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
    SELECT true, public.is_rsvp_open(inv.wedding_slug)
    FROM public.invitations AS inv
    WHERE inv.wedding_slug = p_wedding_slug;
$$;


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


--
-- Name: stamp_rsvp_deletion(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.stamp_rsvp_deletion() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
BEGIN
    IF NEW.deleted_at IS NULL THEN
        NEW.deleted_by := NULL;                       -- restore: authorship is cleared
    ELSIF NEW.deleted_at IS DISTINCT FROM OLD.deleted_at THEN
        NEW.deleted_by := auth.uid();                 -- new deletion: author is whoever ran it
    ELSE
        NEW.deleted_by := OLD.deleted_by;             -- editing an already deleted row: author intact
    END IF;
    RETURN NEW;
END;
$$;


--
-- Name: sync_rsvp_legacy_columns(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.sync_rsvp_legacy_columns() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
BEGIN
    IF NEW.answers IS NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.answers ? 'fullName' THEN
        NEW.full_name := NEW.answers ->> 'fullName';
    END IF;
    IF NEW.answers ? 'attending' THEN
        NEW.attending := (NEW.answers -> 'attending')::boolean;
    END IF;
    IF NEW.answers ? 'dietaryOptions' THEN
        NEW.dietary_options := COALESCE(
            ARRAY(SELECT jsonb_array_elements_text(NEW.answers -> 'dietaryOptions')),
            ARRAY[]::text[]
        );
    END IF;

    NEW.dietary_other := NULLIF(NEW.answers ->> 'dietaryOther', '');
    NEW.bus_option    := NULLIF(NEW.answers ->> 'busOption', '');
    NEW.song_request  := NULLIF(NEW.answers ->> 'songRequest', '');
    NEW.message       := NULLIF(NEW.answers ->> 'message', '');

    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_audit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_audit (
    id bigint NOT NULL,
    response_id bigint,
    entity text NOT NULL,
    wedding_slug text NOT NULL,
    action text NOT NULL,
    actor_id uuid,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT admin_audit_action_check CHECK ((action = ANY (ARRAY['updated'::text, 'deleted'::text, 'restored'::text, 'schedule_changed'::text, 'corrected'::text]))),
    CONSTRAINT admin_audit_entity_check CHECK ((entity = ANY (ARRAY['rsvp_response'::text, 'invitation'::text]))),
    CONSTRAINT admin_audit_response_required CHECK (((entity = 'rsvp_response'::text) = (response_id IS NOT NULL)))
);


--
-- Name: admin_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.admin_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: admin_audit_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.admin_audit_id_seq OWNED BY public.admin_audit.id;


--
-- Name: invitation_admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invitation_admins (
    invitation_id text NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT invitation_admins_invitation_id_check CHECK (((char_length(btrim(invitation_id)) >= 1) AND (char_length(btrim(invitation_id)) <= 100)))
);


--
-- Name: invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invitations (
    wedding_slug text NOT NULL,
    event_date_utc timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    rsvp_deadline_utc timestamp with time zone,
    rsvp_override text,
    purge_warning_sent_at timestamp with time zone,
    CONSTRAINT invitations_rsvp_override_check CHECK (((rsvp_override IS NULL) OR (rsvp_override = ANY (ARRAY['open'::text, 'closed'::text]))))
);


--
-- Name: rsvp_responses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rsvp_responses (
    id bigint NOT NULL,
    wedding_slug text DEFAULT 'boda-general'::text NOT NULL,
    full_name text NOT NULL,
    attending boolean NOT NULL,
    dietary_options text[] DEFAULT '{}'::text[] NOT NULL,
    dietary_other text,
    bus_option text,
    song_request text,
    message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    form_id text,
    form_version integer,
    locale text,
    answers jsonb,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    deleted_by uuid,
    identity_discriminator smallint,
    submission_intent text,
    identity_key text GENERATED ALWAYS AS ((lower(btrim(full_name)) || COALESCE(('#'::text || (identity_discriminator)::text), ''::text))) STORED,
    CONSTRAINT rsvp_responses_answers_check CHECK (((answers IS NULL) OR ((jsonb_typeof(answers) = 'object'::text) AND (octet_length((answers)::text) <= 16384)))),
    CONSTRAINT rsvp_responses_bus_option_check CHECK (((bus_option IS NULL) OR (char_length(bus_option) <= 100))),
    CONSTRAINT rsvp_responses_dietary_options_check CHECK (((cardinality(dietary_options) <= 16) AND (octet_length((dietary_options)::text) <= 2000))),
    CONSTRAINT rsvp_responses_dietary_other_check CHECK (((dietary_other IS NULL) OR (char_length(dietary_other) <= 1000))),
    CONSTRAINT rsvp_responses_form_id_check CHECK (((form_id IS NULL) OR ((char_length(btrim(form_id)) >= 1) AND (char_length(btrim(form_id)) <= 100)))),
    CONSTRAINT rsvp_responses_form_version_check CHECK (((form_version IS NULL) OR (form_version >= 1))),
    CONSTRAINT rsvp_responses_full_name_check CHECK (((char_length(btrim(full_name)) >= 1) AND (char_length(btrim(full_name)) <= 200))),
    CONSTRAINT rsvp_responses_locale_check CHECK (((locale IS NULL) OR ((char_length(locale) >= 2) AND (char_length(locale) <= 35)))),
    CONSTRAINT rsvp_responses_message_check CHECK (((message IS NULL) OR (char_length(message) <= 4000))),
    CONSTRAINT rsvp_responses_song_request_check CHECK (((song_request IS NULL) OR (char_length(song_request) <= 500))),
    CONSTRAINT rsvp_responses_wedding_slug_check CHECK (((char_length(btrim(wedding_slug)) >= 1) AND (char_length(btrim(wedding_slug)) <= 100)))
);


--
-- Name: COLUMN rsvp_responses.identity_discriminator; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.rsvp_responses.identity_discriminator IS 'Allocated by resolve_rsvp_identity() for a guest who shares a name with someone who already answered. NULL for the first holder of a name. Never accepted from the client.';


--
-- Name: COLUMN rsvp_responses.submission_intent; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.rsvp_responses.submission_intent IS 'Request field read and cleared by resolve_rsvp_identity(): correction or namesake. Always NULL at rest.';


--
-- Name: rsvp_responses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rsvp_responses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: rsvp_responses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.rsvp_responses_id_seq OWNED BY public.rsvp_responses.id;


--
-- Name: admin_audit id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_audit ALTER COLUMN id SET DEFAULT nextval('public.admin_audit_id_seq'::regclass);


--
-- Name: rsvp_responses id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rsvp_responses ALTER COLUMN id SET DEFAULT nextval('public.rsvp_responses_id_seq'::regclass);


--
-- Name: admin_audit admin_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_audit
    ADD CONSTRAINT admin_audit_pkey PRIMARY KEY (id);


--
-- Name: invitation_admins invitation_admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation_admins
    ADD CONSTRAINT invitation_admins_pkey PRIMARY KEY (invitation_id, user_id);


--
-- Name: invitations invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_pkey PRIMARY KEY (wedding_slug);


--
-- Name: rsvp_responses rsvp_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rsvp_responses
    ADD CONSTRAINT rsvp_responses_pkey PRIMARY KEY (id);


--
-- Name: admin_audit_wedding_occurred_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX admin_audit_wedding_occurred_idx ON public.admin_audit USING btree (wedding_slug, occurred_at DESC);


--
-- Name: rsvp_responses_form_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rsvp_responses_form_id_idx ON public.rsvp_responses USING btree (wedding_slug, form_id);


--
-- Name: rsvp_responses_identity_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX rsvp_responses_identity_unique ON public.rsvp_responses USING btree (wedding_slug, identity_key) WHERE (deleted_at IS NULL);


--
-- Name: invitations invitations_default_rsvp_deadline; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER invitations_default_rsvp_deadline BEFORE INSERT ON public.invitations FOR EACH ROW EXECUTE FUNCTION public.default_rsvp_deadline();


--
-- Name: rsvp_responses record_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER record_audit AFTER UPDATE ON public.rsvp_responses FOR EACH ROW EXECUTE FUNCTION public.record_rsvp_response_audit();


--
-- Name: invitations record_schedule_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER record_schedule_audit AFTER UPDATE ON public.invitations FOR EACH ROW EXECUTE FUNCTION public.record_invitation_schedule_audit();


--
-- Name: rsvp_responses rsvp_responses_05_require_open; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER rsvp_responses_05_require_open BEFORE INSERT ON public.rsvp_responses FOR EACH ROW EXECUTE FUNCTION public.require_rsvp_open();


--
-- Name: rsvp_responses rsvp_responses_10_sync_legacy_columns; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER rsvp_responses_10_sync_legacy_columns BEFORE INSERT OR UPDATE ON public.rsvp_responses FOR EACH ROW EXECUTE FUNCTION public.sync_rsvp_legacy_columns();


--
-- Name: rsvp_responses rsvp_responses_20_resolve_identity; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER rsvp_responses_20_resolve_identity BEFORE INSERT ON public.rsvp_responses FOR EACH ROW EXECUTE FUNCTION public.resolve_rsvp_identity();


--
-- Name: rsvp_responses rsvp_responses_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER rsvp_responses_set_updated_at BEFORE UPDATE ON public.rsvp_responses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: rsvp_responses rsvp_responses_stamp_deletion; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER rsvp_responses_stamp_deletion BEFORE UPDATE ON public.rsvp_responses FOR EACH ROW EXECUTE FUNCTION public.stamp_rsvp_deletion();


--
-- Name: admin_audit admin_audit_response_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_audit
    ADD CONSTRAINT admin_audit_response_id_fkey FOREIGN KEY (response_id) REFERENCES public.rsvp_responses(id) ON DELETE CASCADE;


--
-- Name: invitation_admins invitation_admins_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation_admins
    ADD CONSTRAINT invitation_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: rsvp_responses rsvp_responses_wedding_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rsvp_responses
    ADD CONSTRAINT rsvp_responses_wedding_slug_fkey FOREIGN KEY (wedding_slug) REFERENCES public.invitations(wedding_slug) ON DELETE CASCADE NOT VALID;


--
-- Name: admin_audit; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.admin_audit ENABLE ROW LEVEL SECURITY;

--
-- Name: admin_audit admin_audit_select_admin; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY admin_audit_select_admin ON public.admin_audit FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.invitation_admins membership
  WHERE ((membership.invitation_id = admin_audit.wedding_slug) AND (membership.user_id = ( SELECT auth.uid() AS uid))))));


--
-- Name: invitation_admins; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.invitation_admins ENABLE ROW LEVEL SECURITY;

--
-- Name: invitation_admins invitation_admins_select_own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY invitation_admins_select_own ON public.invitation_admins FOR SELECT TO authenticated USING ((user_id = ( SELECT auth.uid() AS uid)));


--
-- Name: invitations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.invitations ENABLE ROW LEVEL SECURITY;

--
-- Name: invitations invitations_select_admin; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY invitations_select_admin ON public.invitations FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.invitation_admins membership
  WHERE ((membership.invitation_id = invitations.wedding_slug) AND (membership.user_id = ( SELECT auth.uid() AS uid))))));


--
-- Name: invitations invitations_update_admin; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY invitations_update_admin ON public.invitations FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.invitation_admins membership
  WHERE ((membership.invitation_id = invitations.wedding_slug) AND (membership.user_id = ( SELECT auth.uid() AS uid)))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM public.invitation_admins membership
  WHERE ((membership.invitation_id = invitations.wedding_slug) AND (membership.user_id = ( SELECT auth.uid() AS uid))))));


--
-- Name: rsvp_responses; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.rsvp_responses ENABLE ROW LEVEL SECURITY;

--
-- Name: rsvp_responses rsvp_responses_insert_anon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rsvp_responses_insert_anon ON public.rsvp_responses FOR INSERT TO anon WITH CHECK ((((char_length(btrim(wedding_slug)) >= 1) AND (char_length(btrim(wedding_slug)) <= 100)) AND ((char_length(btrim(full_name)) >= 1) AND (char_length(btrim(full_name)) <= 200)) AND (cardinality(dietary_options) <= 16) AND (octet_length((dietary_options)::text) <= 2000) AND (form_id IS NOT NULL) AND ((char_length(btrim(form_id)) >= 1) AND (char_length(btrim(form_id)) <= 100)) AND (form_version IS NOT NULL) AND (form_version >= 1) AND (locale IS NOT NULL) AND ((char_length(locale) >= 2) AND (char_length(locale) <= 35)) AND (answers IS NOT NULL) AND (jsonb_typeof(answers) = 'object'::text) AND (octet_length((answers)::text) <= 16384) AND (answers ? 'fullName'::text) AND (answers ? 'attending'::text) AND ((answers ->> 'fullName'::text) = full_name) AND ((answers -> 'attending'::text) = to_jsonb(attending)) AND public.is_rsvp_open(wedding_slug)));


--
-- Name: rsvp_responses rsvp_responses_select_admin; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rsvp_responses_select_admin ON public.rsvp_responses FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.invitation_admins membership
  WHERE ((membership.invitation_id = rsvp_responses.wedding_slug) AND (membership.user_id = ( SELECT auth.uid() AS uid))))));


--
-- Name: rsvp_responses rsvp_responses_update_admin; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rsvp_responses_update_admin ON public.rsvp_responses FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.invitation_admins membership
  WHERE ((membership.invitation_id = rsvp_responses.wedding_slug) AND (membership.user_id = ( SELECT auth.uid() AS uid)))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM public.invitation_admins membership
  WHERE ((membership.invitation_id = rsvp_responses.wedding_slug) AND (membership.user_id = ( SELECT auth.uid() AS uid))))));


--
-- PostgreSQL database dump complete
--



-- Privileges
GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;
GRANT ALL ON FUNCTION public.default_rsvp_deadline() TO anon;
GRANT ALL ON FUNCTION public.default_rsvp_deadline() TO authenticated;
GRANT ALL ON FUNCTION public.default_rsvp_deadline() TO service_role;
REVOKE ALL ON FUNCTION public.get_pending_purge_warnings(p_days_before integer) FROM PUBLIC;
GRANT ALL ON FUNCTION public.get_pending_purge_warnings(p_days_before integer) TO service_role;
REVOKE ALL ON FUNCTION public.get_rsvp_status(p_wedding_slug text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.get_rsvp_status(p_wedding_slug text) TO anon;
GRANT ALL ON FUNCTION public.get_rsvp_status(p_wedding_slug text) TO authenticated;
GRANT ALL ON FUNCTION public.get_rsvp_status(p_wedding_slug text) TO service_role;
REVOKE ALL ON FUNCTION public.is_rsvp_open(p_wedding_slug text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.is_rsvp_open(p_wedding_slug text) TO anon;
GRANT ALL ON FUNCTION public.is_rsvp_open(p_wedding_slug text) TO authenticated;
GRANT ALL ON FUNCTION public.is_rsvp_open(p_wedding_slug text) TO service_role;
REVOKE ALL ON FUNCTION public.purge_all_expired_rsvp() FROM PUBLIC;
GRANT ALL ON FUNCTION public.purge_all_expired_rsvp() TO service_role;
REVOKE ALL ON FUNCTION public.record_invitation_schedule_audit() FROM PUBLIC;
GRANT ALL ON FUNCTION public.record_invitation_schedule_audit() TO service_role;
REVOKE ALL ON FUNCTION public.record_rsvp_response_audit() FROM PUBLIC;
GRANT ALL ON FUNCTION public.record_rsvp_response_audit() TO service_role;
REVOKE ALL ON FUNCTION public.require_rsvp_open() FROM PUBLIC;
GRANT ALL ON FUNCTION public.require_rsvp_open() TO service_role;
REVOKE ALL ON FUNCTION public.resolve_rsvp_identity() FROM PUBLIC;
GRANT ALL ON FUNCTION public.resolve_rsvp_identity() TO service_role;
REVOKE ALL ON FUNCTION public.rsvp_invitation_state(p_wedding_slug text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.rsvp_invitation_state(p_wedding_slug text) TO anon;
GRANT ALL ON FUNCTION public.rsvp_invitation_state(p_wedding_slug text) TO authenticated;
GRANT ALL ON FUNCTION public.rsvp_invitation_state(p_wedding_slug text) TO service_role;
GRANT ALL ON FUNCTION public.set_updated_at() TO anon;
GRANT ALL ON FUNCTION public.set_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.set_updated_at() TO service_role;
REVOKE ALL ON FUNCTION public.stamp_rsvp_deletion() FROM PUBLIC;
GRANT ALL ON FUNCTION public.stamp_rsvp_deletion() TO service_role;
REVOKE ALL ON FUNCTION public.sync_rsvp_legacy_columns() FROM PUBLIC;
GRANT ALL ON FUNCTION public.sync_rsvp_legacy_columns() TO service_role;
GRANT ALL ON TABLE public.admin_audit TO service_role;
GRANT SELECT ON TABLE public.admin_audit TO authenticated;
GRANT ALL ON SEQUENCE public.admin_audit_id_seq TO anon;
GRANT ALL ON SEQUENCE public.admin_audit_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.admin_audit_id_seq TO service_role;
GRANT ALL ON TABLE public.invitation_admins TO service_role;
GRANT SELECT ON TABLE public.invitation_admins TO authenticated;
GRANT ALL ON TABLE public.invitations TO service_role;
GRANT SELECT ON TABLE public.invitations TO authenticated;
GRANT UPDATE(rsvp_deadline_utc) ON TABLE public.invitations TO authenticated;
GRANT UPDATE(rsvp_override) ON TABLE public.invitations TO authenticated;
GRANT ALL ON TABLE public.rsvp_responses TO service_role;
GRANT SELECT ON TABLE public.rsvp_responses TO authenticated;
GRANT INSERT(wedding_slug) ON TABLE public.rsvp_responses TO anon;
GRANT INSERT(full_name) ON TABLE public.rsvp_responses TO anon;
GRANT UPDATE(full_name) ON TABLE public.rsvp_responses TO authenticated;
GRANT INSERT(attending) ON TABLE public.rsvp_responses TO anon;
GRANT UPDATE(attending) ON TABLE public.rsvp_responses TO authenticated;
GRANT INSERT(dietary_options) ON TABLE public.rsvp_responses TO anon;
GRANT UPDATE(dietary_options) ON TABLE public.rsvp_responses TO authenticated;
GRANT INSERT(dietary_other) ON TABLE public.rsvp_responses TO anon;
GRANT UPDATE(dietary_other) ON TABLE public.rsvp_responses TO authenticated;
GRANT INSERT(bus_option) ON TABLE public.rsvp_responses TO anon;
GRANT UPDATE(bus_option) ON TABLE public.rsvp_responses TO authenticated;
GRANT INSERT(song_request) ON TABLE public.rsvp_responses TO anon;
GRANT UPDATE(song_request) ON TABLE public.rsvp_responses TO authenticated;
GRANT INSERT(message) ON TABLE public.rsvp_responses TO anon;
GRANT UPDATE(message) ON TABLE public.rsvp_responses TO authenticated;
GRANT INSERT(form_id) ON TABLE public.rsvp_responses TO anon;
GRANT INSERT(form_version) ON TABLE public.rsvp_responses TO anon;
GRANT INSERT(locale) ON TABLE public.rsvp_responses TO anon;
GRANT UPDATE(locale) ON TABLE public.rsvp_responses TO authenticated;
GRANT INSERT(answers) ON TABLE public.rsvp_responses TO anon;
GRANT UPDATE(answers) ON TABLE public.rsvp_responses TO authenticated;
GRANT UPDATE(updated_at) ON TABLE public.rsvp_responses TO authenticated;
GRANT UPDATE(deleted_at) ON TABLE public.rsvp_responses TO authenticated;
GRANT UPDATE(deleted_by) ON TABLE public.rsvp_responses TO authenticated;
GRANT INSERT(submission_intent) ON TABLE public.rsvp_responses TO anon;
GRANT ALL ON SEQUENCE public.rsvp_responses_id_seq TO service_role;
GRANT USAGE ON SEQUENCE public.rsvp_responses_id_seq TO anon;
