export {weddingInvitation} from './invitation'
export {weddingConfig} from './legacyConfig'
export type {WeddingConfig} from './legacyConfig'
export {esMessages} from './locales/es'
export type {WeddingMessageKey} from './locales/es'
export {weddingCatalogLoaders} from './locales/loaders'
export type {WeddingLocale} from './locales/types'
