#!/bin/sh
# Applies the shims, then every migration in filename order, then the assertions.
# Stops at the first failure so the exit code is meaningful in CI.
set -e

echo "==> applying shims"
psql -v ON_ERROR_STOP=1 -q -f /sql/00-shims.sql

for migration in /sql/migrations/*.sql; do
    echo "==> applying $(basename "$migration")"
    psql -v ON_ERROR_STOP=1 -q -f "$migration"
done

echo "==> verifying schema and behaviour"
psql -v ON_ERROR_STOP=1 -q -f /sql/99-verify.sql

for suite in /sql/pgtap/*.test.sql; do
    echo "==> pgTAP $(basename "$suite")"
    psql -v ON_ERROR_STOP=1 -q -f "$suite"
done

# Regenerating the snapshot from the applied migrations is what keeps `schema.sql` from drifting
# again. `--schema=public` leaves the platform shims out; migrations stay the executable source.
if [ -w /out ]; then
    echo "==> regenerating schema.sql"
    {
        echo "-- Generated by \`pnpm run db:verify\` from the applied migrations."
        echo "-- Do not edit by hand. Migrations remain the executable source of truth."
        echo "-- Structure and privileges only; it never contains RSVP data."
        echo
        # `\restrict` carries a token pg_dump randomises on every run; keeping it would make
        # the CI drift check fail on identical schemas.
        pg_dump --schema-only --no-owner --no-privileges --schema=public | grep -vE '^\\(un)?restrict '
        echo
        echo "-- Privileges"
        pg_dump --schema-only --no-owner --schema=public | grep -E '^(GRANT|REVOKE)' || true
    } > /out/schema.sql
fi

echo "==> all migrations applied and verified"
