import type {ThemeDefinition} from './types.ts'

export const themes = {
    royal: {
        colors: {
            background: '#F8F9FB',
            primary: '#1B3A6B',
            action: '#1B3A6B',
            onAction: '#FFFFFF',
            text: '#0F2347',
            surface: '#EEF1F7',
            border: '#C9A84C',
            muted: '#656D7A',
            controlBorder: '#80691F',
            success: '#176B45',
            successSurface: '#DCEFE5',
            danger: '#9B2C3D',
            dangerSurface: '#F7E1E4'
        },
        typography: {
            heading: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
            body: '"Josefin Sans", sans-serif'
        },
        googleFonts: ['Josefin+Sans:wght@300;400;600'],
        shadows: {
            card: '0 4px 20px rgba(27, 58, 107, 0.08)',
            cardLarge: '0 12px 40px rgba(27, 58, 107, 0.12)',
            cardSmall: '0 2px 8px rgba(27, 58, 107, 0.05)'
        },
        radius: {card: '12px', small: '8px', large: '16px', extraLarge: '24px'},
        composition: {
            sectionGap: '4rem',
            sectionGapWide: '5rem',
            ornamentGap: '3.5rem',
            ornamentGapWide: '5rem',
            editorialMaxWidth: '56rem',
            mediaMaxWidth: '22.5rem',
        },
        motion: {revealDuration: '0.8s', revealDistance: '18px', interactionDuration: '0.25s'},
        surfaces: {contentCardOpacity: '70%', formCardOpacity: '80%'},
        decoration: {ornamentColor: '#C9A84C', ornamentOpacity: '0.9'},
        iconography: {interfaceStrokeWidth: '1.75'},
    },
    boho: {
        colors: {
            background: '#F5EFE6',
            primary: '#7C9A6E',
            action: '#4F6B45',
            onAction: '#FFFFFF',
            text: '#4A3728',
            surface: '#EDE4D8',
            border: '#D4C5B0',
            muted: '#786148',
            controlBorder: '#77624B',
            success: '#35603A',
            successSurface: '#DFEADC',
            danger: '#8B3037',
            dangerSurface: '#F3DDDB'
        },
        typography: {heading: '"Cormorant Garamond", serif', body: '"Nunito", sans-serif'},
        googleFonts: ['Cormorant+Garamond:ital,wght@0,400;0,600;1,400', 'Nunito:wght@300;400;600'],
        shadows: {
            card: '0 4px 20px rgba(124, 154, 110, 0.1)',
            cardLarge: '0 12px 40px rgba(124, 154, 110, 0.15)',
            cardSmall: '0 2px 8px rgba(124, 154, 110, 0.06)'
        },
        radius: {card: '16px', small: '10px', large: '20px', extraLarge: '28px'},
        composition: {
            sectionGap: '4.5rem',
            sectionGapWide: '5.5rem',
            ornamentGap: '4rem',
            ornamentGapWide: '5.5rem',
            editorialMaxWidth: '54rem',
            mediaMaxWidth: '23rem',
        },
        motion: {revealDuration: '0.9s', revealDistance: '14px', interactionDuration: '0.3s'},
        surfaces: {contentCardOpacity: '78%', formCardOpacity: '84%'},
        decoration: {ornamentColor: '#B08A57', ornamentOpacity: '0.78'},
        iconography: {interfaceStrokeWidth: '1.6'},
    },
    dark: {
        colors: {
            background: '#0D0D0D',
            primary: '#C9A84C',
            action: '#C9A84C',
            onAction: '#0D0D0D',
            text: '#F0EAD6',
            surface: '#1A1A1A',
            border: '#2E2E2E',
            muted: '#9CA3AF',
            controlBorder: '#777777',
            success: '#7DD3A8',
            successSurface: '#163C2B',
            danger: '#FF9AA8',
            dangerSurface: '#4A1F27'
        },
        typography: {heading: '"Cormorant Garamond", serif', body: '"Lato", sans-serif'},
        googleFonts: ['Cormorant+Garamond:ital,wght@0,400;0,600;1,400', 'Lato:wght@300;400;700'],
        shadows: {
            card: '0 4px 20px rgba(0, 0, 0, 0.4)',
            cardLarge: '0 12px 40px rgba(0, 0, 0, 0.5)',
            cardSmall: '0 2px 8px rgba(0, 0, 0, 0.3)'
        },
        radius: {card: '12px', small: '8px', large: '16px', extraLarge: '24px'},
        composition: {
            sectionGap: '4rem',
            sectionGapWide: '4.5rem',
            ornamentGap: '3.5rem',
            ornamentGapWide: '4.5rem',
            editorialMaxWidth: '56rem',
            mediaMaxWidth: '22.5rem',
        },
        motion: {revealDuration: '0.65s', revealDistance: '12px', interactionDuration: '0.2s'},
        surfaces: {contentCardOpacity: '82%', formCardOpacity: '88%'},
        decoration: {ornamentColor: '#D7BD78', ornamentOpacity: '0.82'},
        iconography: {interfaceStrokeWidth: '1.6'},
    },
    magnolia: {
        colors: {
            background: '#FBF6F0',
            primary: '#B76E79',
            action: '#8F4F5D',
            onAction: '#FFFFFF',
            text: '#3D1F28',
            surface: '#F2E8E4',
            border: '#C9A27A',
            muted: '#805F6D',
            controlBorder: '#8C5962',
            success: '#2F6B4F',
            successSurface: '#E0EFE6',
            danger: '#8F3445',
            dangerSurface: '#F5DFE3'
        },
        typography: {heading: '"Cormorant Garamond", serif', body: '"Raleway", sans-serif'},
        googleFonts: ['Cormorant+Garamond:ital,wght@0,400;0,600;1,400', 'Raleway:wght@300;400;600'],
        shadows: {
            card: '0 4px 20px rgba(183, 110, 121, 0.1)',
            cardLarge: '0 12px 40px rgba(183, 110, 121, 0.15)',
            cardSmall: '0 2px 8px rgba(183, 110, 121, 0.06)'
        },
        radius: {card: '14px', small: '9px', large: '18px', extraLarge: '26px'},
        composition: {
            sectionGap: '4.5rem',
            sectionGapWide: '5.5rem',
            ornamentGap: '4rem',
            ornamentGapWide: '5.5rem',
            editorialMaxWidth: '54rem',
            mediaMaxWidth: '22rem',
        },
        motion: {revealDuration: '0.9s', revealDistance: '16px', interactionDuration: '0.3s'},
        surfaces: {contentCardOpacity: '75%', formCardOpacity: '84%'},
        decoration: {ornamentColor: '#C9A27A', ornamentOpacity: '0.8'},
        iconography: {interfaceStrokeWidth: '1.6'},
    },
    linen: {
        colors: {
            background: '#FBF9F6',
            primary: '#4A5343',
            action: '#4A5343',
            onAction: '#FFFFFF',
            text: '#2C3029',
            surface: '#F5F3EF',
            border: '#D4C5B0',
            muted: '#696F62',
            controlBorder: '#74644D',
            success: '#356243',
            successSurface: '#E2ECE3',
            danger: '#8B3434',
            dangerSurface: '#F2E0DE'
        },
        typography: {heading: '"Playfair Display", serif', body: '"Montserrat", sans-serif'},
        googleFonts: ['Playfair+Display:ital,wght@0,400;0,600;1,400', 'Montserrat:wght@300;400;600'],
        shadows: {
            card: '0 4px 20px rgba(74, 83, 67, 0.08)',
            cardLarge: '0 12px 40px rgba(74, 83, 67, 0.12)',
            cardSmall: '0 2px 8px rgba(74, 83, 67, 0.05)'
        },
        radius: {card: '12px', small: '8px', large: '16px', extraLarge: '24px'},
        composition: {
            sectionGap: '4.25rem',
            sectionGapWide: '5.25rem',
            ornamentGap: '3.75rem',
            ornamentGapWide: '5.25rem',
            editorialMaxWidth: '52rem',
            mediaMaxWidth: '22.5rem',
        },
        motion: {revealDuration: '0.75s', revealDistance: '12px', interactionDuration: '0.22s'},
        surfaces: {contentCardOpacity: '72%', formCardOpacity: '82%'},
        decoration: {ornamentColor: '#B59A6A', ornamentOpacity: '0.72'},
        iconography: {interfaceStrokeWidth: '1.5'},
    },
    lavender: {
        colors: {
            background: '#F7F4FC',
            primary: '#6E5FAE',
            action: '#4B3F8F',
            onAction: '#FFFFFF',
            text: '#241B3D',
            surface: '#ECE6F7',
            border: '#B79B6B',
            muted: '#5C5470',
            controlBorder: '#6B5C99',
            success: '#2E6B4A',
            successSurface: '#DFF0E4',
            danger: '#8B3350',
            dangerSurface: '#F6E0E7'
        },
        typography: {heading: '"Cormorant Garamond", serif', body: '"Nunito", sans-serif'},
        googleFonts: ['Cormorant+Garamond:ital,wght@0,400;0,600;1,400', 'Nunito:wght@300;400;600'],
        shadows: {
            card: '0 4px 20px rgba(110, 95, 174, 0.10)',
            cardLarge: '0 12px 40px rgba(110, 95, 174, 0.15)',
            cardSmall: '0 2px 8px rgba(110, 95, 174, 0.06)'
        },
        radius: {card: '15px', small: '9px', large: '19px', extraLarge: '27px'},
        composition: {
            sectionGap: '4.5rem',
            sectionGapWide: '5.5rem',
            ornamentGap: '4rem',
            ornamentGapWide: '5.5rem',
            editorialMaxWidth: '54rem',
            mediaMaxWidth: '22.5rem',
        },
        motion: {revealDuration: '0.85s', revealDistance: '16px', interactionDuration: '0.28s'},
        surfaces: {contentCardOpacity: '76%', formCardOpacity: '85%'},
        decoration: {ornamentColor: '#C2A672', ornamentOpacity: '0.82'},
        iconography: {interfaceStrokeWidth: '1.6'},
    },
    terracotta: {
        colors: {
            background: '#FBF3EA',
            primary: '#A8511F',
            action: '#973F16',
            onAction: '#FFFFFF',
            text: '#3D2B1F',
            surface: '#F3E3D0',
            border: '#BF9165',
            muted: '#6E4A35',
            controlBorder: '#8C5A34',
            success: '#2F6B45',
            successSurface: '#E1EFE2',
            danger: '#8B3B2E',
            dangerSurface: '#F5E1DB'
        },
        typography: {heading: '"Playfair Display", serif', body: '"Lato", sans-serif'},
        googleFonts: ['Playfair+Display:ital,wght@0,400;0,600;1,400', 'Lato:wght@300;400;700'],
        shadows: {
            card: '0 4px 20px rgba(168, 81, 31, 0.10)',
            cardLarge: '0 12px 40px rgba(168, 81, 31, 0.15)',
            cardSmall: '0 2px 8px rgba(168, 81, 31, 0.06)'
        },
        radius: {card: '10px', small: '7px', large: '14px', extraLarge: '22px'},
        composition: {
            sectionGap: '4.25rem',
            sectionGapWide: '5.25rem',
            ornamentGap: '3.75rem',
            ornamentGapWide: '5.25rem',
            editorialMaxWidth: '52rem',
            mediaMaxWidth: '22.5rem',
        },
        motion: {revealDuration: '0.75s', revealDistance: '14px', interactionDuration: '0.24s'},
        surfaces: {contentCardOpacity: '74%', formCardOpacity: '83%'},
        decoration: {ornamentColor: '#C99A66', ornamentOpacity: '0.78'},
        iconography: {interfaceStrokeWidth: '1.55'},
    },
} as const satisfies Record<string, ThemeDefinition>

export type ThemeId = keyof typeof themes
