import {focusShadows, globalRadius} from '../tokens'
import type {ThemeDefinition} from './types'

export function toCssVariables(theme: ThemeDefinition): Record<string, string> {
    return {
        '--color-wedding-bg': theme.colors.background,
        '--color-wedding-primary': theme.colors.primary,
        '--color-wedding-action': theme.colors.action,
        '--color-wedding-on-action': theme.colors.onAction,
        '--color-wedding-text': theme.colors.text,
        '--color-wedding-surface': theme.colors.surface,
        '--color-wedding-border': theme.colors.border,
        '--color-wedding-muted': theme.colors.muted,
        '--color-wedding-control-border': theme.colors.controlBorder,
        '--color-wedding-success': theme.colors.success,
        '--color-wedding-success-surface': theme.colors.successSurface,
        '--color-wedding-danger': theme.colors.danger,
        '--color-wedding-danger-surface': theme.colors.dangerSurface,
        '--font-heading': theme.typography.heading,
        '--font-body': theme.typography.body,
        '--shadow-card': theme.shadows.card,
        '--shadow-card-lg': theme.shadows.cardLarge,
        '--shadow-card-sm': theme.shadows.cardSmall,
        '--radius-card': theme.radius.card,
        '--radius-sm': theme.radius.small,
        '--radius-lg': theme.radius.large,
        '--radius-xl': theme.radius.extraLarge,
        '--radius-focus': globalRadius.focus,
        '--radius-pill': globalRadius.pill,
        '--shadow-focus': focusShadows.input,
        '--theme-section-gap': theme.composition.sectionGap,
        '--theme-section-gap-wide': theme.composition.sectionGapWide,
        '--theme-ornament-gap': theme.composition.ornamentGap,
        '--theme-ornament-gap-wide': theme.composition.ornamentGapWide,
        '--theme-editorial-max-width': theme.composition.editorialMaxWidth,
        '--theme-media-max-width': theme.composition.mediaMaxWidth,
        '--theme-reveal-duration': theme.motion.revealDuration,
        '--theme-reveal-distance': theme.motion.revealDistance,
        '--theme-interaction-duration': theme.motion.interactionDuration,
        '--theme-content-card-opacity': theme.surfaces.contentCardOpacity,
        '--theme-form-card-opacity': theme.surfaces.formCardOpacity,
        '--theme-ornament-color': theme.decoration.ornamentColor,
        '--theme-ornament-opacity': theme.decoration.ornamentOpacity,
        '--theme-interface-icon-stroke-width': theme.iconography.interfaceStrokeWidth,
    }
}
